# 13. Cross-Tab

In [3]:
import pandas as pd
df=pd.read_excel("survey.xlsx")
df

# crosstab - pandas

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

In [4]:
pd.crosstab(df.Nationality,df.Handedness,margins=True) ##showing the frequency of the variable
#margins shows the total count

Handedness   Left  Right  All
Nationality
Bangadesh       2      0    2
China           2      1    3
India           2      1    3
USA             1      3    4
All             7      5   12

In [5]:
pd.crosstab(df.Sex,[df.Handedness,df.Nationality],margins=True) #col,row

Handedness       Left                 Right           All
Nationality Bangadesh China India USA China India USA
Sex
Female              1     1     0   0     1     0   2   5
Male                1     1     2   1     0     1   1   7
All                 2     2     2   1     1     1   3  12

In [6]:
pd.crosstab([df.Nationality,df.Sex],[df.Handedness],margins=True)

Handedness          Left  Right  All
Nationality Sex
Bangadesh   Female     1      0    1
            Male       1      0    1
China       Female     1      1    2
            Male       1      0    1
India       Male       2      1    3
USA         Female     0      2    2
            Male       1      1    2
All                    7      5   12

In [9]:
pd.crosstab([df.Sex],[df.Handedness],margins=True) # hover over the crosstab function, click shift+tab, it show the documentation

Handedness  Left  Right  All
Sex
Female         2      3    5
Male           5      2    7
All            7      5   12

In [7]:
pd.crosstab([df.Sex],[df.Handedness],margins=True,normalize="index") #normalize shows the percentage

Handedness      Left     Right
Sex
Female      0.400000  0.600000
Male        0.714286  0.285714
All         0.583333  0.416667

In [8]:
import numpy as np
pd.crosstab([df.Sex],[df.Handedness],values=df.Age,aggfunc=np.average)

Handedness  Left  Right
Sex
Female      44.5   31.0
Male        31.2   28.0

##### Read Database records into pandas dataframe and write it back

In [16]:
pip install PyMySQL

Collecting PyMySQLNote: you may need to restart the kernel to use updated packages.
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.0.2

In [19]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\kcjc608\anaconda3\lib\site-packages (1.4.22)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\kcjc608\anaconda3\lib\site-packages (from sqlalchemy) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import sqlalchemy

In [26]:
from sqlalchemy import create_engine
db = sqlalchemy.SQLAlchemy(engine)
from flask_sqlalchemy import SQLAlchemy

NameError: name 'sqlalchemy' is not defined

In [42]:
engine=sqlalchemy.create_engine('mysql+pymysql://root:White@123@127.0.0.1:3306/application')

In [43]:
df=pd.read_sql_table("customers",engine)
df

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '123@127.0.0.1' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)